
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_USERDATA = 'SET_USERDATA';

export const GET_WORKORDERS = 'GET_WORKORDERS';

export const GET_WORKORDERS_SUCCESS = 'GET_WORKORDERS_SUCCESS';

export const NAVIGATION = 'NAVIGATION'

export const SET_WORKORDER_UUID = 'SET_WORKORDER_UUID'

